---
- name: Create configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_directory }}/conf/nginx.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 644
  notify: Reload Nginx

- name: “Create {{ nginx_vhosts_folder }}”
  file:
    path: "{{ nginx_vhosts_folder }}"
    state: directory

- name: Put django.conf
  template:
    src: conf.d/django.conf.j2
    dest: "{{ nginx_vhosts_folder }}/django.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 644
  notify: Reload Nginx

- name: Put nginx.service
  template:
    src: systemd/nginx.service.j2
    dest: "/etc/systemd/system/nginx.service"
    owner: root
    group: root
    mode: 644

- name: Daemon reload systemd
  command: systemctl daemon-reload

- name: Enable and run nginx 
  service:
    name: nginx
    state: started
    enabled: true
